settings:
  title: 'Status Page'
  url: 'https://status-page.eidam.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: keep.neu5.repl.co # unique identifier
    name: keep.neu5.repl.co
    description: 'You write code. They handle the rest.' # default=empty
    url: 'https://keep.neu5.repl.co/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: keep1.neu5.repl.co
    name: keep1.neu5.repl.co
    description: 'Built for anything connected to the Internet.'
    url: 'https://keep1.neu5.repl.co/'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: chat.neu5.repl.co
    name: chat.neu5.repl.co
    url: 'https://chat.neu5.repl.co/room/@Neu'
    method: GET
    expectStatus: 200
